; --- Общие настройки ---
[env]
platform = espressif32
framework = arduino
monitor_speed = 115200
lib_deps = olikraus/U8g2

; --- 1. Ваша плата: ESP32 WROOM с OLED и батареей ---
[env:esp32_wroom_oled]
board = esp32dev
build_flags = 
    -D HAS_OLED=1
    -D OLED_SDA=5
    -D OLED_SCL=4

; --- 2. ESP32-C3 Super Mini (Без экрана, для релиза) ---
[env:esp32-c3-supermini]
board = esp32-c3-devkitm-1
build_flags = 
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1